### ISSUE TITLE
do you have any suggestion what kind of modem can use this code?

### ISSUE THREAD

**Issue by steve21124** [faucamp/python-gsmmodem#2]
like specific sample gsm modem that can be purchased from amazon and ready to use this code

**Comment by faucamp** [comment]
Most USB GSM modems should work just fine (the code is written to be generic), but due to my location (za) I cannot easily recommend a specific one from amazon.com. The code is tested using a Huawei K3715 and several old Wavecom serial port modems - any Huawei should be a safe bet. 

That said, if you have a modem that does not work with the code, please use the "identify-modem.py" script in the "tools" dir in debug mode, and I'll add support for it. Run the script using the debug flag, i.e.:

./identify-modem.py -d /dev/ttyUSB0

Then just open an issue with the output of that command, it'll be much appreciated!
